title: Книги

description: Выписки из книг, прочитанных мной

baseurl: "/books"

url: "https://sgromkov.github.io"

remote_theme: pmarsceill/just-the-docs

search_enabled: true

aux_links:
    "About me":
      - "//sgromkov.github.io/"
