title: gromkov.me/docs

description: Документация сама себя не напишет

baseurl: "/docs"

url: "https://gromkov.me"

remote_theme: pmarsceill/just-the-docs

search_enabled: false

aux_links:
    "Сережа Громков":
      - "//gromkov.me/"
    "Вконтакте":
      - "https://vk.com/t_a_n_f"
    "LinkedIn":
      - "https://ru.linkedin.com/in/sgromkov"
    "Github":
      - "https://github.com/sgromkov"

footer_content: "Copyright &copy; 2020 Sergey Gromkov."