title: Документация

description: Сама себя не напишет

baseurl: "/docs"

url: "https://gromkov.me"

remote_theme: pmarsceill/just-the-docs

search_enabled: false

aux_links:
    "Сережа Громков":
      - "//gromkov.me/"

footer_content: "Copyright &copy; 2020 Sergey Gromkov."